#!/usr/bin/env bash
# Bash script that will display infor about the subdomains

dig_dns () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dig_dns "$1" "www"
  dig_dns "$1" "lb-01"
  dig_dns "$1" "web-01"
  dig_dns "$1" "web-02"
elif [ "$#" == 2 ]
then
  dig_dns "$1" "$2"
fi
