#!/usr/bin/env bash

get_record_info() {
  local domain=$1
  local subdomain=$2

  local record_info=$(dig +short "$subdomain.$domain")

  if [ -z "$record_info" ]; then
    echo "The subdomain $subdomain does not have any DNS records."
  else
    local record_type=$(echo "$record_info" | awk '{print $4}')
    local destination=$(echo "$record_info" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  fi
}

domain=$1
subdomains=("www" "lb-01" "web-01" "web-02")

for subdomain in "${subdomains[@]}"; do
  get_record_info "$domain" "$subdomain"
done
