#!/usr/bin/env bash
# install nginx and listen to port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx start 
