#!/usr/bin/env bash
sudo apt-get -y update

# Install Nginx
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

# Create a custom HTML page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx start
