#!/usr/bin/env bash
# install nginx

apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
sudo sh -c 'echo 'Hello World!' > /var/www/html/index.nginx-debian.html'
service nginx restart 
