#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure /etc/haproxy/haproxy.cfg
cat > /etc/haproxy/haproxy.cfg <<- EOF
global
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  maxconn 256

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000

frontend http-in
  bind *:80
  default_backend servers

backend servers
  mode http
  balance roundrobin 
  option httpclose
  option forwardfor
  cookie SERVERINSERT insert indirect nocache
  server 281411-web-01 54.146.88.8:80 check
  server 281411-web-02 54.146.88.136:80 check
EOF

# Enable HAproxy service
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
