#!/usr/bin/env bash
#ckage repositories
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg
# Edit the HAProxy file
printf %s "global
   log 127.0.0.1 local0 notice
   maxconn 2000
   user haproxy
   group haproxy

defaults
   log    global
   mode   http
   option httplog
   retries 3
   option redispatch
   timeout connect 5000
   timeout client 30000
   timeout server 30000
   errorfile 400 /etc/haproxy/errors/400.http
   errorfile 403 /etc/haproxy/errors/403.http
   errorfile 408 /etc/haproxy/errors/408.http
   errorfile 500 /etc/haproxy/errors/500.http
   errorfile 502 /etc/haproxy/errors/502.http
   errorfile 503 /etc/haproxy/errors/503.http
   errorfile 504 /etc/haproxy/errors/504.http

frontend deol-frontend
    bind *:80
    timeout client  30000
    default_backend deol-backend
backend deol-backend
    balance roundrobin
    timeout connect 3000
    timeout server 30000
    server 281411-web-01 54.146.88.8:80 check
    server 281411-web-02 54.146.88.136:80 check
" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
