#!/usr/bin/env bash
# This is a script that pings an IP address passed as an argument.

# Check if there is an argument.
if [ $# -eq 0 ]; then
	echo "Usages: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
