#!/usr/bin/env bash
# This is a script that pings an IP address passed as an argument.

# Check if there is an argument.
if [ $# -eq 0 ]; then
	echo "Usages: $0 {IP_ADDRESS}"
	exit 1
fi

# Get the IP address from cmd-line arg.
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 "$ip_address"
