#!/usr/bin/env bash
# This is a script that pings an IP address passed as an argument.

# Check if there is an argument.
if [ $# -eq 0 ]; then
	echo "Usages: $0 {IP_ADDRESS}"
else
	ip_address="$1"
	ping -c 5 "$ip_address"
fi
