#!/usr/bin/env bash
# This is a script that Creates the file /var/run/myscript.pid containing its PID,
# Displays To infinity and beyond indefinitely,
# Displays I hate the kill command when receiving a SIGTERM signal,
# Displays Y U no love me?! when receiving a SIGINT signal,
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or
# SIGTERM signal.

pid_file="/var/run/myscript.pid"
m="I hate the kill command"
n="Y U no love me?!"
o="To infinity and beyond"

quit_handler() {
	rm "$pid_file"
	exit 0
}

echo $$ > "$pid_file"

while true; do
	echo "$o"
	sleep 2
	trap 'echo "$n"' SIGINT
	trap 'echo "$m" && quit_handler' SIGTERM
	trap 'quit_handler' SIGQUIT
done
