#!/usr/bin/env bash
# This is a script 101-manage_my_process that manages manage_my_process:
# Requirements:
# When passing the argument start:
#	Starts manage_my_process
#	Creates a file containing its PID in /var/run/my_process.pid
#	Displays manage_my_process started
# When passing the argument stop:
#	Stops manage_my_process
#	Deletes the file /var/run/my_process.pid
#	Displays manage_my_process stopped
# When passing the argument restart
#	Stops manage_my_process
#	Deletes the file /var/run/my_process.pid
#	Starts manage_my_process
#	Creates a file containing its PID in /var/run/my_process.pid
#	Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passei


p_file="/var/run/my_process.pid"
m="manage_my_process started"
n="manage_my_process restarted"
o="manage_my_process stopped"

if [ "${1}" == "start" ]; then
	./manage_my_process &
	touch $p_file
	echo "$!" > $p_file
	echo "$m"
elif [ "${1}" == "stop" ]; then
	echo "$o"
	kill "$(cat $p_file)"
	rm $p_file
elif [ "${1}" == "restart" ]; then
	kill "$(cat $p_file)"
	rm $p_file
	./manage_my_process &
	touch $p_file
	echo "$!" > $p_file
	echo "$n"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
