#!/usr/bin/env bash
# This is a script  that displays the PID, along with the process name,
# of processes whose name contain the word bash.

pid=$(pgrep -f bash)

for p in $pid; do
	dip=$(ps -o comm= -p "$p")
	echo "$p $dip"
done
