#!/usr/bin/env bash
# This is a script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration.
# I am invincible!!! when receiving a SIGTERM signal.

m="To infinity and beyond"
l="I am invincible!!!"

while true; do
	echo "$m"
	sleep 2
	echo "$l"
	trap SIGTERM
done
