#!/usr/bin/env bash
# This is a script that:
# Indefinitely writes I am alive! to the file /tmp/my_process,
# In between every I am alive! message, the program should pause for 2 seconds.

p_file="/tmp/my_process"

while true; do
	echo "I am alive!" >> p_file
	sleep 2
done
