#!/usr/bin/env bash
# This is displays the content of the file /etc/passwd.

while IFS=":" read -r username password userID groupID info homeDirectory commandShell; do
	echo "The user $username is part of the $groupID gang, lives in $homeDirectory and rides $commandShell."
	echo "$userID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
