#!/usr/bin/env bash
# This is displays the content of the file /etc/passwd,
# using the while loop + IFS.

while IFS=: read -r username password userid groupid user_info homedir shell; do
	user_id_info=$(getent passwd "$username")

	echo "The user $username is part of the group $groupid gang, lives in $homedir and rides $shell."
	echo "$userid's place is protected by the passcode $password, more info about the user here: $user_id_info"
	echo
done < /etc/passwd
