#!/usr/bin/env bash
# This script uses while loop to display "Best School" 10 times
# but for the 9th iteration, displays Best School Hi.

i=0
while ((i < 10)); do
	if ((i == 8)); then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
