#!/usr/bin/env bash
# This script displays:
# The content of the current directory.
# In a list format
# Where only the part of the name after the first dash is displayed.
# Uses for loop.

content=$(ls)
for file in $content; do
	echo "$file" | cut -d '-' -f2
done
