#!/usr/bin/env bash
# This script gives you information about the school file:
# uses if and else statement.

file="school"
#Check if file exists
if [ -e "$file" ]; then
	echo "school file exists"
	
	#Check if the file is empty
	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	#Check if file is a regular file
	if [ -f "$file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
