#!/usr/bin/env bash
# This is a script that displays all active IPv4 IPs on the
# machine it’s executed on.

ifconfig_output=$(ifconfig)

ipv4_lines=$(echo "$ifconfig_output" | grep -Eo 'inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | awk '{print $2}')

echo "$ipv4_lines"
