#!/usr/bin/env bash
# Bash script to reload Gunicorn

pids=$(pgrep gunicorn)

if [ -z "$pids" ]; then
    echo "No Gunicorn processes found. Make sure Gunicorn is running."
else
    echo "Reloading Gunicorn..."
    echo "$pids" | xargs -I {} kill -HUP {}
    echo "Reload complete."
fi
